### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Bigbike21** [0SoggyMustache0/NaturalFauna#12]
Hey, since the Zawa mod updated today, this mod won't work. it says this:
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from NaturalFauna (faunanatural)
I hope you guys can fix it, cause I enjoy these mods a lot.
Thanks!!

**Comment by gkazan** [comment]
There is not enough information. Post a full crash report on hastebin and link it.

**Comment by Bigbike21** [comment]
[crash-2020-04-05_23.59.37-client.txt](https://github.com/0SoggyMustache0/NaturalFauna/files/4434985/crash-2020-04-05_23.59.37-client.txt)

**Comment by JoelZBub** [comment]
I tried to duplicate this and can't

**Comment by Bigbike21** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 4/5/20 11:59 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from NaturalFauna (faunanatural)
Caused by: java.lang.NullPointerException
	at net.minecraftforge.fml.common.registry.EntityRegistry.addSpawn(EntityRegistry.java:258)
	at com.ikerleon.naturalfaunamod.proxies.CommonProxy.postInit(CommonProxy.java:120)
	at com.ikerleon.naturalfaunamod.NaturalFaunaMain.postInit(NaturalFaunaMain.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:754)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.15.4
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 370501496 bytes (353 MB) / 1073741824 bytes (1024 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 7 total; -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 18 mods loaded, 18 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                 | Version           | Source                                        | Signature                                |
	|:----- |:------------------ |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJ | minecraft          | 1.12.2            | minecraft.jar                                 | None                                     |
	| LCHIJ | mcp                | 9.42              | minecraft.jar                                 | None                                     |
	| LCHIJ | FML                | 8.0.99.99         | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LCHIJ | forge              | 14.23.5.2847      | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LCHIJ | biomesoplenty      | 7.0.1.2441        | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar | None                                     |
	| LCHIJ | bookworm           | 1.12.2-2.5.1      | bookworm-1.12.2-2.5.1.jar                     | None                                     |
	| LCHIJ | butterflies        | 1.12.2-1.0.3      | butterflies-1.12.2-1.0.3.jar                  | None                                     |
	| LCHIJ | ctm                | MC1.12.2-1.0.2.31 | CTM-MC1.12.2-1.0.2.31.jar                     | None                                     |
	| LCHIJ | jei                | 4.15.0.291        | jei_1.12.2-4.15.0.291.jar                     | None                                     |
	| LCHIJ | chisel             | MC1.12.2-1.0.2.45 | Chisel-MC1.12.2-1.0.2.45.jar                  | None                                     |
	| LCHIJ | craftablenametag   | 1.0.0             | CN+(MC+1.12.2).jar                            | None                                     |
	| LCHIJ | dynamictrees       | 1.12.2-0.9.7      | DynamicTrees-1.12.2-0.9.7.jar                 | None                                     |
	| LCHIJ | dynamictreesbop    | 1.12.2-1.4.1e     | DynamicTreesBOP-1.12.2-1.4.1e.jar             | None                                     |
	| LCHIJ | journeymap         | 1.12.2-5.7.1      | journeymap-1.12.2-5.7.1.jar                   | None                                     |
	| LCHIJ | zawa               | 1.12.2-2.0.2      | zawa-1.12.2-2.0.2.jar                         | 3ee471ded1bba54aa82f4f5ca5ca82dd67b8ef42 |
	| LCHIJ | lilcritters        | 1.12.2-1.0.0.1    | lilcritters-1.12.2-1.0.0.1.jar                | None                                     |
	| LCHIE | faunanatural       | 1.12.2-1.5.1      | NaturalFauna+Mod-1.12.2-1.5.1.jar             | None                                     |
	| LCHI  | travellersbackpack | 1.0.23.23         | TravellersBackpack-1.12.2-1.0.23.23.jar       | None                                     |

	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-14.5.22' Renderer: 'Intel(R) Iris(TM) Plus Graphics 655'
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 18
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 INTEL-14.5.22
	OpenGlRenderer: Intel(R) Iris(TM) Plus Graphics 655
	OpenGlVendor: Intel Inc.
	CpuCount: 8

**Comment by Bigbike21** [comment]
This is what's in it.

**Comment by JoelZBub** [comment]
I can't duplicate _**the issue**_.
Pasting a wall of text with the contents of the file you posted earlier isn't going to help anyone duplicate the issue.

**Comment by JoelZBub** [comment]
Reinstall your mods.

**Comment by Bigbike21** [comment]
All of them?
Cause I tried to with Zawa and natural fauna

**Comment by Bigbike21** [comment]
And that didn't work

**Comment by Bigbike21** [comment]
I'm sorry, but I don't know what you mean by the issue... I thought maybe you couldn't open the file, that's why I copy and pasted it. Can I provide this issue for you?

**Comment by JoelZBub** [comment]
Can not duplicate your problem (the issue) in my game.

**Comment by Bigbike21** [comment]
Okay, now I get it, sorry to have bothered you. Thanks for the info.
