### ISSUE TITLE
It keeps crashing in the mod initialization phase

### ISSUE THREAD

**Issue by Shadow4495** [0SoggyMustache0/NaturalFauna#9]
The game crashed whilst initializing game
Error: java.lang.NoSuchMethodError: org.zawamod.util.SpawnData.getBiomeIDS([Lnet/minecraft/world/biome/Biome;)[Ljava/lang/String;
crash report:---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 7/15/19 1:14 PM
Description: Initializing game

java.lang.NoSuchMethodError: org.zawamod.util.SpawnData.getBiomeIDS([Lnet/minecraft/world/biome/Biome;)[Ljava/lang/String;
	at com.ikerleon.naturalfaunamod.configuration.NaturalFaunaConfig$Spawns.<init>(NaturalFaunaConfig.java:32)
	at com.ikerleon.naturalfaunamod.configuration.NaturalFaunaConfig.<clinit>(NaturalFaunaConfig.java:29)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.common.config.ConfigManager.sync(ConfigManager.java:160)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:613)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.ikerleon.naturalfaunamod.configuration.NaturalFaunaConfig$Spawns.<init>(NaturalFaunaConfig.java:32)
	at com.ikerleon.naturalfaunamod.configuration.NaturalFaunaConfig.<clinit>(NaturalFaunaConfig.java:29)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.common.config.ConfigManager.sync(ConfigManager.java:160)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:613)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 315908656 bytes (301 MB) / 805306368 bytes (768 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 25 mods loaded, 25 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version           | Source                                            | Signature                                |
	|:----- |:------------------- |:----------------- |:------------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft           | 1.12.2            | minecraft.jar                                     | None                                     |
	| LC    | mcp                 | 9.42              | minecraft.jar                                     | None                                     |
	| LC    | FML                 | 8.0.99.99         | forge-1.12.2-14.23.5.2838.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge               | 14.23.5.2838      | forge-1.12.2-14.23.5.2838.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | biomesoplenty       | 7.0.1.2427        | BiomesOPlenty-1.12.2-7.0.1.2427-universal.jar     | None                                     |
	| LC    | craftstudioapi      | 1.0.0             | CraftStudio-API-1.12.2.jar                        | None                                     |
	| LC    | animania            | 1.6.2             | animania-1.12.2-1.6.2.jar                         | None                                     |
	| LC    | betteranimalsplus   | 6.0.3             | betteranimalsplus-1.12.2-6.0.3.jar                | None                                     |
	| LC    | bookworm            | 1.12.2-2.2.0      | bookworm+-+2.2.0+(1.12.2).jar                     | None                                     |
	| LC    | cfm                 | 6.3.0             | cfm-6.3.0-mc1.12.2.jar                            | None                                     |
	| LC    | ctm                 | MC1.12.2-0.3.3.22 | CTM-MC1.12.2-0.3.3.22.jar                         | None                                     |
	| LC    | chisel              | MC1.12.2-0.2.1.35 | Chisel-MC1.12.2-0.2.1.35.jar                      | None                                     |
	| LC    | chiselsandbits      | 14.22             | Chisels-and-Bits-Mod-1.12.2.jar                   | None                                     |
	| LC    | customnpcs          | 1.12              | Custom-NPCs-Mod-1.12.2.jar                        | None                                     |
	| LC    | mocreatures         | 12.0.5            | DrZharks MoCreatures Mod-12.0.5.jar               | None                                     |
	| LC    | exoticbirds         | 1.0               | Exotic-Birds-Mod-1.12.2 (1).jar                   | None                                     |
	| LC    | familiarfauna       | 1.0.11            | FamiliarFauna-1.12.2-1.0.11.jar                   | None                                     |
	| LC    | zawa                | 1.12.1-1.1.0      | Zoo-Animals-1.12.2.jar                            | None                                     |
	| LC    | moon-core           | 7.0               | moon-core+7.0+(1.12).jar                          | None                                     |
	| L     | faunanatural        | 1.12.2-1.4.0      | NaturalFauna+Mod-1.12.2-1.4.0 (2).jar             | None                                     |
	| L     | pmp                 | 1.12.1            | Plant-Mega-Pack-Mod-1.12.2.jar                    | None                                     |
	| L     | worldedit           | 6.1.10-SNAPSHOT   | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |
	| L     | xaerominimap        | 1.17.2            | Xaeros-Minimap-Mod-1.12.2 (1).jar                 | None                                     |
	| L     | zoocraftdiscoveries | 1.0               | Zoocraft-Discoveries-Mod-1.12.2.jar               | None                                     |
	| L     | llibrary            | 1.7.18            | LLibrary-1.12.2.jar                               | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.35' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2838
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.35, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: John Smith Legacy JSC 1.12.2 v9.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz

**Comment by Mnesikos** [comment]
Update your mods. You're using Zawa 1.1.0 when the current version is 1.6.0 and does not even support moon-core anymore. Natural Fauna's curseforge page states which versions of Zawa is compatible with each release.

**Comment by JoelZBub** [comment]
I'm noticing more people using zawa 1.1.0
Time to start looking at which site this is coming from.
The official site is curseforge, which serves the latest version.
@Shadow4495 Would you mind telling us where you downloaded zawa ?

**Comment by Shadow4495** [comment]
I understand now, I might've gotten it from Minecraft six
